### ISSUE TITLE
Release python binary for inclusion in projects

### ISSUE THREAD

**Issue by shs96c** [philwo/bazelisk#25]
My users use a combination of Linux, OS X, and Windows, but can be relied upon to have a basic python installation present. Since they may not have installed the various pips required by bazelisk, it would be useful if bazelisk were a single deployable python binary (similar to a [PEX](https://github.com/pantsbuild/pex)) that could be included at the root of the project.

This would provide multi-platform support easily without bloating the repo. Having a binary per platform won't work in this case, since I'm working on an Open Source project, and it's hard enough to get people to install the baseline requirements.

**Comment by philwo** [comment]
Hi Simon,

Thanks so much for the feedback :) Bazelisk (Python version) is written to not require any dependencies from pip. It only uses things included in the Python standard library.

That said, PEX looks like a cool thing to use and I’ll have a look at it! It might even allow me to simplify the code, if it becomes easy to safely include third-party dependencies like Requests.

By the way: Is the recently added Go version of Bazelisk useful for you? Maybe not, because you want to check in a single binary into your repo, but just wanted to point it out. Both versions support the same features and pass the same test suite on all platforms.

Cheers,
Philipp

**Comment by shs96c** [comment]
Ah! Fantastic news that it only includes things from the standard library :)

The Go version isn't practical for my project given the expected usage, but it's good to know that they both support the same set of features.

I'll close this issue, since it's possible to include that single file and get this working. Excellent work, and thank you!
