### ISSUE TITLE
Take advantage of //tools/bazel?

### ISSUE THREAD

**Issue by ashi009** [philwo/bazelisk#48]
Just a random thought, this seems a great approach for handling bazel version issue in a non-managed environment but asking users to install this is still a challenge.

Given that bazel will try to invoke //tools/bazel if exists, so how about placing a shell script there to download and run the proper version of bazel instead?

**Comment by philwo** [comment]
Hi @ashi009!

I totally understand that it can be hard to get users to install Bazelisk. Building upon your idea, you could simply check bazelisk.py into your repository as `tools/bazel` and it should just work. :)

Note that only the `bazel` command that gets installed by the Bazel installer has the behavior of invoking //tools/bazel, because that's actually a shell script wrapper, not a real Bazel binary. This behavior is not something built into Bazel itself, so if someone does not use the installer and instead installs the Bazel binary directly, it would not work.

**Comment by ashi009** [comment]
Good call. Thanks!
