### ISSUE TITLE
//tools/bazel wrapper not executed

### ISSUE THREAD

**Issue by emidln** [philwo/bazelisk#51]
It seems bazelisk installs a bazel version that doesn't use the `bazel.sh` wrapper found in the standard distribution. It also doesn't add a `bazel-real` to the `PATH`. This prevents `//tools/bazel` wrappers from working.

**Comment by philwo** [comment]
Can you please point me to one such wrapper? I'd like to check how I can make Bazelisk work with it.

**Comment by emidln** [comment]
I think we'd just need to download a version of bazel built with the bazel.sh support[0], and then unpack that into a directory. The way the packaging for bazel.sh[1][2] works, the script is installed as `bazel` and the actual binary is installed as `bazel-real`. The protocol for usage is such that if the script detects a `$(bazel info workspace)/tools/bazel` wrapper, it is executed instead of `bazel-real`. The wrapper then calls `$BAZEL_REAL` (if it wants to). This lets you do arbitrary things (like setting environment variables or adding `--config`s based on OS) prior to running bazel as well as choose to call something other than bazel for custom integration (i.e. a `bazel publish` that calls to some shell script to publish binaries). 

It looks like the official installer[0] is built with `bazel.sh`. Homebrew also packages `bazel.sh`. Currently, it looks like bazelisk downloads the exe binaries directly.

A nonsensical sample script at `//tools/bazel` would be something like

```bash
#!/bin/sh

# flip a coin
FLIP=$(($(($RANDOM%10))%2))

if [ $FLIP -eq 1 ]; then
    cowsay -d "build cow down; try again later"
else
    cowsay "build cow thanks you for your business"
    $BAZEL_REAL "$@"
fi
```


[0] https://github.com/bazelbuild/bazel/blob/ce91f76e659cee6940d0f5e10c2bbd7e43be76d4/scripts/packages/BUILD#L117
[1] https://github.com/bazelbuild/bazel/blob/master/scripts/packages/bazel.sh
[2] https://github.com/bazelbuild/bazel/blob/master/scripts/packages/BUILD#L101

**Comment by philwo** [comment]
Ah, I see. I think we could easily add this to Bazelisk using the following logic:

```
if the file tools/bazel exists:
  set environment variable BAZEL_REAL = path to downloaded Bazel
  execute tools/bazel
  # the tools/bazel script is now responsible to execute $BAZEL_REAL
else:
  execute downloaded Bazel
```

This should reproduce what the shell script does, right?

We also have to add a check whether our own currently running Bazelisk binary is the same as `$workspace_root/tools/bazel`, otherwise we'll run into a loop when someone installs Bazelisk itself as `tools/bazel`.

**Comment by emidln** [comment]
I think that's enough.

> We also have to add a check whether our own currently running Bazelisk binary is the same as $workspace_root/tools/bazel, otherwise we'll run into a loop when someone installs Bazelisk itself as tools/bazel.

I didn't consider installing bazelisk as `tools/bazel`, but that would certainly be a use case.

**Comment by akshayjshah** [comment]
Are you open to a PR that implements this? (And are new features going into the Python version, the Go version, or both?)

**Comment by philwo** [comment]
@akshayjshah Yes, I'd be happy to take a PR! Thank you :)

I see that you already signed the Google CLA, so there would be no blockers in accepting it.

I like to keep the Python and Go version in sync if possible. We have some secondary features that are only in the Go version, like the `migrate` support, but they're not essential for Bazelisk's main job. This feature seems important and relevant, so we should add it to both versions, as the difference in behavior will otherwise be pretty confusing.

Note that there's an open PR that implements a simple version of this for Python only: https://github.com/philwo/bazelisk/pull/46 - maybe you can figure out with @hperl who wants to do what.

**Comment by akshayjshah** [comment]
PR open that covers Python and Go, addressing the feedback on the previous PR. Happy to hand some or all of it over to @hperl if desired.

**Comment by philwo** [comment]
Fixed via https://github.com/philwo/bazelisk/pull/53 - thanks!
